### ISSUE TITLE
How would I set postconfig parameter setting that is not defined as ENV?

### ISSUE THREAD

**Issue by rbozan** [mikenye/docker-postfix#13]
Hi, I have a question:

I would like to change one of the postconfig parameter setting for my specific use case, which is basically having `home_mailbox = Maildir/` in my main.cf. However I can't set it using `RUN postconf -e home_mailbox = Maildir/` in my Dockerfile which is based on this image, but I can set it when the container is started using `docker exec`. I assume because of the generating of the config file which happens after using `postconf`.

What would be the best way to change the config using this Docker image when it has no ENV? Much appreciated.

**Comment by rbozan** [comment]
It seems creating a .sh script, copying it over to /etc/cont-init.d in a Dockerfile with a number higher than all others seem to be sufficient :)

**Comment by mikenye** [comment]
You're correct. The postfix config files are (re)built via the scripts in `/etc/cont-init.d` every time the container is started. Adding your script with a higher number ensures your changes won't be clobbered.
