### ISSUE TITLE
enable submission port 587

### ISSUE THREAD

**Issue by maxadamo** [mikenye/docker-postfix#33]
I am reading on several sources, that these days we should use port 587, instead of port 25. 
For instance, there is something here: https://www.cloudflare.com/it-it/learning/email-security/smtp-port-25-587/

As I understand, to enable the submission port in Postifx is only matter of uncommenting a single line in master.cf. 

I tried it inside the container, changing the line and issuing a `postfix reload` and it seems to work. 

@mikenye I am sure you are more knowledgable than me on this topic, and what is your opinion in this regard? I am going to create a PR.

**Comment by maxadamo** [comment]
fixed by #34 

I noticed that there was a variable `$POSTFIX_MASTERCF_FILE` and I used it everywhere, and some of the corrections have been by the auto-format tool that I use

**Comment by mikenye** [comment]
Hi @maxadamo, thanks for the issue and PR (which is merged).

My organisation has moved to MS365 for email, so I no longer have this container front-ending our Exchange :(.

Accordingly I'm somewhat out of the loop on this, however adding this functionality is a good idea.

Are you able to update the README.md with the new variables?

**Comment by maxadamo** [comment]
@mikenye I think I did it. Now I'm commuting and I'm writing from my.phone. Can you check the logs for the Readme file? Is that enough?

**Comment by mikenye** [comment]
I can't see anything yet. There's no rush, mate. :-)

**Comment by mikenye** [comment]
Oh you'd already done it, and I totally missed it. 🤦 
My apologies.
